a=str(input("Ho ten: "))
b=float(input("So ngay cong: "))
c=float(input("Don gia ngay cong: "))
d=float(input("He so phu cap: "))
e=int(input("Tam ung: "))
print("Nhan vien ",a,sep="")
print("Co tien luong=",c*b*d,sep="")
print("Tam ung=",e,sep="")
print("Thuc linh=",(c*b*d)-e,sep="")
